version: '3'
services:
 mymongo:
  image: mongo

  ports:
   - "27017"
  volumes:
   - data:/data/db
  networks:
   - net1
 todo:
  image: bijoythomask/todo.mongo:v3

  depends_on:
    - mymongo
  ports:
    - "8090:8080"
  networks:
   - net1
  environment:
   - server=mymongo
volumes:
 data:
  driver: local
networks:
 net1:
  external:
      name: swarm-spring-demo
  # Use a custom driver
  #driver: pring_demo_net